### ISSUE TITLE
В проекте не создается папка allure result,после команд gradlew clean test,gradlew allurereport

### ISSUE THREAD

**Issue by Ginnyelf** [Ginnyelf/pattern-task-1#1]
# Описание
В проекте не создается папка allure result,после команд gradlew clean test,gradlew allurereport

# Локация дефекта
![image](https://github.com/Ginnyelf/pattern-task-1/assets/125185653/7a4ad571-ee4f-4810-87d6-5c1918b4dca0)

# Шаги воспроизведения
1. Открыть проект pattern task 1 https://github.com/Ginnyelf/pattern-task-1
2. Внести необходимые зависимости и плагины в build.gradle для построения allurereport
3. Запустить в терминале jar файл
4. Прописать в терминале команду ./gradlew clean test
5. Прописать в терминале команду ./gradlew allurereport
6. Открыть путь build/allure в проекте

*Ожидаемый результат.* Должна появится папка allure result (build/allure/allure result)
*Фактический результат.* Появилась папка allure,но в ней нет allure result

# Скриншот

![image](https://github.com/Ginnyelf/pattern-task-1/assets/125185653/776c3c29-0b25-41a8-8aa2-44ded02dba66)

# Окружение
* **Операционная система:** Windows 10 Домашняя для одного языка,Версия 21H2
* **IDEA:** IntelliJ IDEA 2022.3.2 (Community edition)
* **Java:** OpenJDK11

**Comment by andrew-pahomov** [comment]
Выполняйте команду        
`./gradlew allureserve`         
и отчет откроется в браузере

**Comment by JaneShumikhina** [comment]
![image](https://github.com/Ginnyelf/pattern-task-1/assets/125185653/aa1f5a51-c64d-4136-b450-c155de76dc8c)

**Comment by JaneShumikhina** [comment]
![image](https://github.com/Ginnyelf/pattern-task-1/assets/125185653/24977217-7e23-4bdd-9aee-6c2b439c0990)
Папка появилась после прогона тестов.
